### PR TITLE
Generate changelogs that show the commits between tags

### LINKED ISSUE #49: Add description and website to github homepage
On https://github.com/mozilla-neutrino/neutrino-dev/ there's "No description or website provided." which makes this project look, well, immature ;)

### LINKED ISSUE #311: devServer with open=true hangs on "Building project"
If you specify `open: true` opt with `devServer` then console gets stuck on "Building project" forever. (It still does output errors on recompilations though).

```  neutrino.use(['neutrino-preset-react', {
    devServer: {
      port: opts.port,
      disableHostCheck: true,
      historyApiFallback: true,
      open: true,
      contentBase: opts.contentBase
    },
    babel: {
      presets: [
        ['babel-preset-env', {
          targets: {browsers: ['last 2 versions']}
        }]
      ]
    }
  }])
```

### PR DESCRIPTION
**Pull request by eliperelman**
For example, this would change the latest changelog to:

---

# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

Generated by [auto-changelog](https://github.com/CookPete/auto-changelog).

### Merged
- Improve error messaging for middleware used with no entry point [`#386`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/386)
- Throw more useful errors when missing commands [`#393`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/393)

### Commits
- Reformat readme headings, favor spectrum over slack (#396) [`78fa05c`](https://github.com/mozilla-neutrino/neutrino-dev/commit/78fa05c203f784ba3380d95fe7423952acf2edd2)
- add notes about setup scripts (#388) [`21c38fb`](https://github.com/mozilla-neutrino/neutrino-dev/commit/21c38fb2356bbdc149c1195a95bb5d4b8f0b53c1)
- Fixes to publishing [`6ea0728`](https://github.com/mozilla-neutrino/neutrino-dev/commit/6ea0728c95ac1a7c061428a8dd7a33db7dfd6192)

### Merged
- Follow-ups to the switch to Lerna [`#372`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/372)

### Commits
- Allow using Jest and Mocha presets without Babel (#379) [`ee2e7ba`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ee2e7ba1d32bbbb7e652eea8ed8041a9c1b2a44d)
- Output logging messages when using watch instead of devServer (#378) [`dbc12fd`](https://github.com/mozilla-neutrino/neutrino-dev/commit/dbc12fd37962b3a9a409dd40b0c3035aeff81c19)
- Dev: fixing typo in yarn lint script [`913a875`](https://github.com/mozilla-neutrino/neutrino-dev/commit/913a8754fc7bb0a1ba4661515d89a6e0e81d4fdc)

### Commits
- Release v7.2.2 [`d399824`](https://github.com/mozilla-neutrino/neutrino-dev/commit/d399824fe61d2494445b2b3bfc4a30c73795b5cd)
- Use source directory for jest code coverage (#369) [`1f09c91`](https://github.com/mozilla-neutrino/neutrino-dev/commit/1f09c91bbbb2c3c7466b6b4923b99c29ccce0e79)
- Remove oao, swap for lerna [`ee6d47d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ee6d47df2ce75a01992e900aaa0bc131bb03523e)

### Commits
- Adding docs for hot middleware updates [`1318ab5`](https://github.com/mozilla-neutrino/neutrino-dev/commit/1318ab565d0e6b0ecd92d77932df994d56775464)
- feat(hot): Include NamedModulesPlugin for better developer experience (#365) [`ac62509`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ac6250907b971024bccb401a584396a419264a39)
- fix: Use cheap-module-eval-source-map for faster recompilation (#366) [`66b5594`](https://github.com/mozilla-neutrino/neutrino-dev/commit/66b559403f0f78e760cbfa7d8bc1664e53173218)

### Commits
- Release v7.1.10 [`190de2d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/190de2db17f00c8a6ee98a7882272d0087fc5c4e)
- Update to the newest version of html-webpack-template (#361) [`238959c`](https://github.com/mozilla-neutrino/neutrino-dev/commit/238959c3ade42a14a8d947b09e9ea64094987dbf)

### Commits
- Release v7.1.3 [`e909de6`](https://github.com/mozilla-neutrino/neutrino-dev/commit/e909de6712593f092d4321708d373b8ad94d65e2)
- Add eslintrc.js to .npmignore (#359) [`943de06`](https://github.com/mozilla-neutrino/neutrino-dev/commit/943de063e01e91fd401fc4ba9bf4ca8866ea8baa)

### Merged
- Upgrade oao/yarn and use --frozen-lockfile with oao bootstrap [`#354`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/354)

### Commits
- Release 7.1.2 [`09b8e92`](https://github.com/mozilla-neutrino/neutrino-dev/commit/09b8e92c9b4957090aa93607f2aa2f00ccbe5159)
- Remove extra keys that are invalid in eslintrc (#358) [`62945b6`](https://github.com/mozilla-neutrino/neutrino-dev/commit/62945b683febabeb306f1c39b5c382ddba2dae85)
- Use latest version of yarn on Travis (#355) [`3d495a8`](https://github.com/mozilla-neutrino/neutrino-dev/commit/3d495a8e98f149b87295875bb113eefe9f1c7a74)

### Commits
- Release v7.1.1 [`ed6be9b`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ed6be9bbbd72e042862c9276b5c5405eb83f4a10)
- Hotfix - bump webpack-chain to guard non-defined chainedmap entries [`2ee3b42`](https://github.com/mozilla-neutrino/neutrino-dev/commit/2ee3b42ddf9c4259088e0f4a7bb07a64bac634c1)

### Commits
- Release 7.1.0 [`ea0a2ce`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ea0a2cec2830365bdd1b9cc9fdf643cd5fde8a72)
- Feature: upgrade webpack-chain to use .before() and .after() (#346) [`3aa2666`](https://github.com/mozilla-neutrino/neutrino-dev/commit/3aa266695336ffb9fcaefb5dd014b534111073b5)
- Preserve ESLint default include when just exclude set (#344) [`bb190c4`](https://github.com/mozilla-neutrino/neutrino-dev/commit/bb190c4fadf0f59d170815611fdf9944a5c4a27b)

### Merged
- Remove unused dependencies [`#339`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/339)
- Misc documentation fixes - part 2 [`#335`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/335)

### Fixed
- Simplify require_test.js, making it pass on Windows (#337) [`#336`](https://github.com/mozilla-neutrino/neutrino-dev/issues/336)

### Commits
- Release 7.0.2 [`7e7ecfc`](https://github.com/mozilla-neutrino/neutrino-dev/commit/7e7ecfc9147df945396ac472b98890e68fce9534)
- Configuration docs nits [`1a707f6`](https://github.com/mozilla-neutrino/neutrino-dev/commit/1a707f6b07d56509738c031918948596858906ce)
- Fix link to babel-minify-webpack-plugin options (#340) [`703da77`](https://github.com/mozilla-neutrino/neutrino-dev/commit/703da77efb6c072cc132656afefe0cc2e5d1cc35)

### Commits
- Release v7.0.1 [`b138b3d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/b138b3dcd5c931e183ad7a05975058367f307ce8)

### Merged
- Upgrading Webpack to v3, merge config as middleware [`#315`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/315)

### Commits
- Release v7.0.0 [`a7f701d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/a7f701dfc05163ec7aab095781f1723cbe978b5c)

### Merged
- Misc documentation fixes [`#325`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/325)

### Fixed
- Make the lint command check .jsx files too (#333) [`#332`](https://github.com/mozilla-neutrino/neutrino-dev/issues/332)

### Commits
- Release v6.2.1 [`dd7c5b3`](https://github.com/mozilla-neutrino/neutrino-dev/commit/dd7c5b39f8e6404ea6c3feb4360c5bd9fc5a85b2)
- Small API docs change to avoid confusion. (#317) [`e994c2d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/e994c2d3d2d4290840d1100485ec823f1affdbc0)

### Merged
- feat: Allow passing any Jest CLI options to neutrino-jest test task [`#313`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/313)

### Commits
- Release v6.2.0 [`8237cda`](https://github.com/mozilla-neutrino/neutrino-dev/commit/8237cda6c4b2dd1d723c0eb75ca5997d28a06cd9)
- chore: Add lint-staged and husky (#314) [`d854f94`](https://github.com/mozilla-neutrino/neutrino-dev/commit/d854f94a591a6557c2f7c7a64dbd7bda2042a518)

### Fixed
- Fixes #311 (#312) [`#311`](https://github.com/mozilla-neutrino/neutrino-dev/issues/311)

### Commits
- Release 6.1.8 [`01d9ae9`](https://github.com/mozilla-neutrino/neutrino-dev/commit/01d9ae9c1ef04c69ade4a627f4511bd02eefe543)

### Commits
- Handle list of errors from test command (#310) [`6ceef02`](https://github.com/mozilla-neutrino/neutrino-dev/commit/6ceef028a61c512aa5562996ce307a6275a2d129)
- Release 6.1.6 [`fff6cbb`](https://github.com/mozilla-neutrino/neutrino-dev/commit/fff6cbb9ac412465ddf286989e06f2b226963801)

### Merged
- Fix hot reload [`#304`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/304)

### Commits
- Release 6.1.5 [`f7977ed`](https://github.com/mozilla-neutrino/neutrino-dev/commit/f7977ed677225200f0662814ac865a0b395906b1)
- Fixing broken middleware links [`21bd4de`](https://github.com/mozilla-neutrino/neutrino-dev/commit/21bd4de12dff79dd12eb173f0cb48796234671b2)
- Make it more clear what the env plugin can be used for (#295) [`127aadd`](https://github.com/mozilla-neutrino/neutrino-dev/commit/127aadd616f81e8962696bb675d07b82dbc54791)

### Commits
- Release v6.1.4 [`7411f0b`](https://github.com/mozilla-neutrino/neutrino-dev/commit/7411f0b3f673cf20ba6409f2ab0de4020cfd6612)
- Correctly override path options for custom options (#293) [`9cf8080`](https://github.com/mozilla-neutrino/neutrino-dev/commit/9cf8080a88a308874cc7a36022ae37473566dd1f)

### Commits
- Release v6.1.2 [`fc85787`](https://github.com/mozilla-neutrino/neutrino-dev/commit/fc8578712d8482ad1f357c0be12e1bd580f07e4d)
- Add an .npmignore to all packages (#291) [`ac0fd0d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ac0fd0d540b85dd62a1da652d8562012e2320ac2)
- Prevent null chunks from preventing naming (#284) [`03dbed0`](https://github.com/mozilla-neutrino/neutrino-dev/commit/03dbed024feff4ec3ddcd3e69eb257dd02669fd1)

### Merged
- Karma coverage [`#282`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/282)

### Commits
- Release v6.1.0 [`1de650c`](https://github.com/mozilla-neutrino/neutrino-dev/commit/1de650c8a9676a5a39fa0fca2910e7ec527cdd74)
- Add &#x60;babel-plugin-istanbul&#x60; to ensure accurate coverage is reported. (#279) [`4846888`](https://github.com/mozilla-neutrino/neutrino-dev/commit/484688860b0efbb26b443afe4e32e285f26566b6)
- Ensure test cases are not run 2x in watch mode. (#280) [`5754b99`](https://github.com/mozilla-neutrino/neutrino-dev/commit/5754b99225029762cbc12fc70e26a3dcbb439e2c)

### Commits
- Release v6.0.5 [`09b5957`](https://github.com/mozilla-neutrino/neutrino-dev/commit/09b59578e885f8d4706f8678368ed3099450ae2b)
- Hashing entire un-named chunk instead of individual modules (#278) [`ec7cf98`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ec7cf98b755c695cafbcc100c4b8e1526177c475)

### Commits
- Release v6.0.4 [`7128bb3`](https://github.com/mozilla-neutrino/neutrino-dev/commit/7128bb3c4aa795b12aa0ede0356170910f18d892)
- Adding ESLint support back to React (#275) [`f3a61ba`](https://github.com/mozilla-neutrino/neutrino-dev/commit/f3a61badb1737beb796578e66ba0ba13622726a1)
- Add Travis badge to README (#270) [`7825767`](https://github.com/mozilla-neutrino/neutrino-dev/commit/78257673f196e70170564dc4f20fb1596b21d7f5)

### Commits
- Release v6.0.3 [`39f2f32`](https://github.com/mozilla-neutrino/neutrino-dev/commit/39f2f327c4f51e2d4969d63fae4d815bff70affb)
- Reject test runners when non-zero exit code (#269) [`1435477`](https://github.com/mozilla-neutrino/neutrino-dev/commit/143547780c368cc985723df3b0ad49695a82b4f2)
- Correct typo (#266) [`d957604`](https://github.com/mozilla-neutrino/neutrino-dev/commit/d9576045e1c5aefcd6f75eca5eb20671946e35e8)

### Commits
- Updating oao, yarn.lock files, travis installation [`82a24dd`](https://github.com/mozilla-neutrino/neutrino-dev/commit/82a24dd9d93962b43555eabc0e3d69b9acdabfd7)
- Releasing v6.0.2 [`0370c89`](https://github.com/mozilla-neutrino/neutrino-dev/commit/0370c892798c4ffacf27bfbdf1794e0fabf8e687)
- Fixing issues in babel merging and dynamic named chunks (#264) [`b02679f`](https://github.com/mozilla-neutrino/neutrino-dev/commit/b02679f8b7bc2a8370ce48039809d666a9fe6d85)

### Merged
- v6 [`#254`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/254)
- Document conditional configuration [`#250`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/250)
- Hotfix/neutrino preset jest/relative alias handling [`#243`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/243)
- Add description how to ignore files in an IDE lint [`#205`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/205)

### Commits
- Releasing v6.0.0 [`8b07eed`](https://github.com/mozilla-neutrino/neutrino-dev/commit/8b07eed958ea06cc3e978a24c8f269e296107d0f)
- Yarn lockfile updates [`3a3f73e`](https://github.com/mozilla-neutrino/neutrino-dev/commit/3a3f73e4375a1d6535c182753dfb378ea38b58bd)
- Changelog [`8aa0b45`](https://github.com/mozilla-neutrino/neutrino-dev/commit/8aa0b457f418170499273b71ebc3d743d287d1f5)

### Merged
- add option for node debugging [`#215`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/215)

### Commits
- Releasing v5.9.0 [`c3d7020`](https://github.com/mozilla-neutrino/neutrino-dev/commit/c3d70200c56c1e4a326246fd6233b160660c4cd4)
- Docs for --debug [`dde1f40`](https://github.com/mozilla-neutrino/neutrino-dev/commit/dde1f406fa985a587e1c8422e0dbac04e1dee24c)
- README update [`a446881`](https://github.com/mozilla-neutrino/neutrino-dev/commit/a446881e891d252b48faec3c7a30aef591f844d8)

### Merged
- Feature/universal entry [`#195`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/195)

### Commits
- Releasing v5.8.0 [`2afdd26`](https://github.com/mozilla-neutrino/neutrino-dev/commit/2afdd26f3e6568cc5aa477b8209d823ce6d5d00f)
- Indent to clarify context change (#191) [`d7688dc`](https://github.com/mozilla-neutrino/neutrino-dev/commit/d7688dc674af187011c114f42f5837f0ce2b880b)

### Merged
- Simplify error logging. [`#148`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/148)

### Commits
- Release v5.7.0 [`9186de6`](https://github.com/mozilla-neutrino/neutrino-dev/commit/9186de6175ab49dcfb710bc93fee45befbb725c6)
- Fixing typo in karma docs [`b3d3c73`](https://github.com/mozilla-neutrino/neutrino-dev/commit/b3d3c7330d247f30e0dd7af5f2d8c39cc1ced38e)
- Fix typo in preset name (#190) [`4a3842f`](https://github.com/mozilla-neutrino/neutrino-dev/commit/4a3842fe24103782e54aba2af2b50ff2b30f51ed)

### Merged
- Consider case when &#x27;core-js&#x27; is located in &#x27;babel-polyfill&#x27; root [`#181`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/181)

### Commits
- Release v5.6.0 [`3f56635`](https://github.com/mozilla-neutrino/neutrino-dev/commit/3f56635381131369279ea54c931c8277ef39aca5)
- Merge branch &#x27;master&#x27; of github.com:mozilla-neutrino/neutrino-dev [`587851b`](https://github.com/mozilla-neutrino/neutrino-dev/commit/587851b1687ad09e20d2d8b3aa496099b7b62e38)
- Setting devServer publicPath to / (#179) [`fbe39af`](https://github.com/mozilla-neutrino/neutrino-dev/commit/fbe39af90ba7aae5352c6c0e14f1d51c32fdac87)

### Merged
- Polyfills [`#173`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/173)

### Commits
- v5.5.0 -&gt; v5.5.1 [`425f3ac`](https://github.com/mozilla-neutrino/neutrino-dev/commit/425f3ac37345b2e7774c7bf013d15abac449bc78)
- Adding getters and setters for path options, options for middleware (#176) [`957645f`](https://github.com/mozilla-neutrino/neutrino-dev/commit/957645f820c5262373096c65ba1cd530b26101eb)
- Set devServer.publicPath to use output.publicPath (#177) [`ebc078a`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ebc078a60f7438e94eafa457ad91cf4c71635c08)

### Merged
- neutrino-middleware-image-loader: Use svg-url-loader for svg rule [`#171`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/171)

### Commits
- Releasing v5.4.0 [`f2c1dfb`](https://github.com/mozilla-neutrino/neutrino-dev/commit/f2c1dfb2a34aaf1c52018697bdbe271cd6b6d92b)
- Fixing incorrect documentation for linting (#169) [`5724b5a`](https://github.com/mozilla-neutrino/neutrino-dev/commit/5724b5a3955233d3e1b582e5ef0b5b5e5603e8a8)
- Update changelog [`20c1065`](https://github.com/mozilla-neutrino/neutrino-dev/commit/20c1065c5c222c97c0957106d34ce72e68270703)

### Commits
- Release v5.3.0 [`aec1cbb`](https://github.com/mozilla-neutrino/neutrino-dev/commit/aec1cbb12e4f1cbab54373010c65626094bdd122)
- Update build executable to respect config stats. (#163) [`ab38cd5`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ab38cd54722aca468e283a207f0b701233d1f478)
- fix eslint-semi-off middleware example (#161) [`e6924e2`](https://github.com/mozilla-neutrino/neutrino-dev/commit/e6924e246fcc968314b00cd779b3009185000d69)

### Commits
- Allow setting karma middleware options as overridable (#160) [`3f90dfd`](https://github.com/mozilla-neutrino/neutrino-dev/commit/3f90dfdfa35a95683f69e7aadf86bbd4b0c3483a)
- neutrino v5.1.1 [`878026a`](https://github.com/mozilla-neutrino/neutrino-dev/commit/878026a96102bfda1760f7717e494c7b45058c6e)
- options.output mis-named as options.build (#159) [`e9a7a36`](https://github.com/mozilla-neutrino/neutrino-dev/commit/e9a7a36c786bdb513a84470bae910341052c2987)

### Commits
- Upgrading webpack-chain to v3.1 (#157) [`d009882`](https://github.com/mozilla-neutrino/neutrino-dev/commit/d009882e6d2dbbefe5c450472e689817dbc753af)
- Releasing v5.1.0 [`adcc04f`](https://github.com/mozilla-neutrino/neutrino-dev/commit/adcc04fbf09b2d2cf285a27d6b89fcbb69b71c8d)
- Adding code coverage with Codacy support (#156) [`9871634`](https://github.com/mozilla-neutrino/neutrino-dev/commit/98716343f75f6de5a5ec9d9853bcc084668afc04)

### Merged
- Adding documention about web publicPath [`#141`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/141)
- Hopefully last round of docs changes for v5 [`#140`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/140)
- Upgrading dependencies [`#139`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/139)
- Validate webpack configuration before running compiler [`#138`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/138)
- Functional refactor [`#137`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/137)
- Resolve packages from parent node_modules folders [`#135`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/135)
- Fix typo in develop function. [`#132`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/132)
- Neutrino webpack [`#127`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/127)
- Rename &#x60;getWebpackOptions&#x60; to &#x60;getWebpackConfig&#x60;. [`#123`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/123)
- Neutrino refactor [`#119`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/119)
- Fixing linting to run for all packages [`#120`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/120)
- Fix link [`#117`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/117)
- Fix svg mime-type [`#115`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/115)
- Adding option-configurable compile targets [`#111`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/111)
- Add support building react-native app [`#88`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/88)
- Defer test configuration overrides until on:test [`#110`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/110)
- Using neutrino to lint itself [`#106`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/106)
- Should generate correct sourcemaps during dev [`#105`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/105)
- eslint [`#102`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/102)
- README updates for v5 [`#103`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/103)
- v5 Docs [`#98`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/98)
- Baseline for Neutrino v5 [`#86`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/86)
- Added coverage support to jest preset [`#76`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/76)
- Add Community section for starter kits [`#78`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/78)
- Add FAQ section [`#62`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/62)

### Commits
- Refining middleware concept, splitting presets into middleware packages [`f202977`](https://github.com/mozilla-neutrino/neutrino-dev/commit/f20297738b1fe7d248ee2c6ae3cbd1a94b060539)
- Updating yarn.lock files [`4b8eb84`](https://github.com/mozilla-neutrino/neutrino-dev/commit/4b8eb8493f0ed73b0a832bdefe059b59644b040e)
- Upgrading to webpack-chain v3, add more tests for full presets [`49b9e29`](https://github.com/mozilla-neutrino/neutrino-dev/commit/49b9e296ff8b73dca534e981f2559da6b47e0eda)

### Merged
- v4.2 [`#54`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/54)
- add eslint-jest-plugin [`#48`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/48)
- Add github repo link to gitbook [`#53`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/53)
- Add website to GitHub homepage. Fixes #49 [`#51`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/51)

### Fixed
- Add website to GitHub homepage. Fixes #49 [`#49`](https://github.com/mozilla-neutrino/neutrino-dev/issues/49)

### Commits
- Throw exception on missing module (#45) [`c1033ae`](https://github.com/mozilla-neutrino/neutrino-dev/commit/c1033ae8b0b212e11770f59a4800ad2a9fbf2399)
- Fix typo in usage example (#52) [`dac5df7`](https://github.com/mozilla-neutrino/neutrino-dev/commit/dac5df78fd4790199b68f7bebc82b6f54d9c6cb6)

### Commits
- Wrong lint base version [`fe5c381`](https://github.com/mozilla-neutrino/neutrino-dev/commit/fe5c38180743e4f48c8b97b9b3209e7ad7971ab5)

### Commits
- Introduce lint base to make lint preset creation much easier (#41) [`b838a0d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/b838a0da54a1c31bbc5a2f5845df1ba42fba31dc)
- Changelogs (#31) [`b32ad66`](https://github.com/mozilla-neutrino/neutrino-dev/commit/b32ad66c7d6b0fc8665633f42d416e6d900ba8f6)
- Docs: learning resources [`2647be7`](https://github.com/mozilla-neutrino/neutrino-dev/commit/2647be77806e7431a8888f94f7c2602db58aeade)

### Merged
- Fix: React lifecycle methods shouldn&#x27;t fail eslint [`#26`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/26)
- Slack badges [`#25`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/25)
- Badge updates [`#24`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/24)

### Commits
- Tagline update [`24900a4`](https://github.com/mozilla-neutrino/neutrino-dev/commit/24900a473ad1a51c46ddc35758816c6161a689a9)

### Commits
- ._. [`02a3983`](https://github.com/mozilla-neutrino/neutrino-dev/commit/02a3983df98446c9b0ffad84f68d05c8378b5a97)
- Major version [`ec22aca`](https://github.com/mozilla-neutrino/neutrino-dev/commit/ec22aca1445388ec957aa80b42ac88c364eec838)

### Commits
- All bump [`065cda7`](https://github.com/mozilla-neutrino/neutrino-dev/commit/065cda76e6908af7bbe773026db42e4bc4b2ca63)
- Bump [`cde3503`](https://github.com/mozilla-neutrino/neutrino-dev/commit/cde350374615a5ae10cf07d0a3cee4460f877422)
- README typo [`a6ad540`](https://github.com/mozilla-neutrino/neutrino-dev/commit/a6ad54050c7fb37aac8f0a6db3a19f486862da46)

### Merged
- Documentation [`#17`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/17)
- Removing base preset, adding Airbnb preset [`#22`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/22)
- Simplify configuration [`#18`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/18)
- Displaying fancier build status during dev server [`#16`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/16)
- Fixes HMR [`#15`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/15)
- Pluggable event architecture mode, new test presets [`#10`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/10)
- add version badges [`#12`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/12)
- HTML update [`#2`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/2)
- Linting changes and new config API [`#1`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/1)
- Migration to webpack 2 [`#10`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/10)
- Init in cli [`#8`](https://github.com/mozilla-neutrino/neutrino-dev/pulls/8)

### Commits
- Attempting to force v4 [`35408a8`](https://github.com/mozilla-neutrino/neutrino-dev/commit/35408a8d240e266261bd004041b3b20c02b32dc3)
- oao upgrade [`4925b1d`](https://github.com/mozilla-neutrino/neutrino-dev/commit/4925b1d39aecf0fcbe73bb31ee2efb3b51e53095)
- Release commands [`a792904`](https://github.com/mozilla-neutrino/neutrino-dev/commit/a7929042030696c68bb65daabb94601a5d4589fc)

### CODE REVIEW

**Comment by edmorley** [comment]
Love this! The existing changelog using dates didn't feel right, and I'd been meaning to suggest doing something like this.

At the moment, since Neutrino isn't using the "fixes" notation recognised by auto-changelog, everything has been split out into "merged" and "commits", which seems a bit arbitrary. Looking at the available templates, I see the now default template (compact) avoids this distinction, and might result in a cleaner changelog? See:
https://github.com/CookPete/auto-changelog/tree/master/templates

**Comment by eliperelman** [comment]
@edmorley definitely! Also don't like the 3 commit limit

https://github.com/CookPete/auto-changelog/issues/11

**Comment by edmorley** [comment]
> Also don't like the 3 commit limit

Yeah me neither - seems a bit arbitrary.

**Comment by eliperelman** [comment]
Alrighty, I have the updated version of auto-changelog here, along with an updated changelog.

**Comment by edmorley** [comment]
What do you think about:

> Looking at the available templates, I see the now default template (compact) avoids this distinction, and might result in a cleaner changelog?

:-)

**Comment by eliperelman** [comment]
Sorry, I tried to imply my agreement with:

> @edmorley definitely

fail

Anyway, the script now doesn't specify the template, so it uses the default one now. 😃

**Comment by eliperelman** [comment]
:tada:

**Comment by eliperelman** [comment]
That looks way better: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/CHANGELOG.md

**Comment by CookPete** [comment]
>>Also don't like the 3 commit limit
>
>Yeah me neither - seems a bit arbitrary.

The commit limit was there to prevent changelogs just [becoming a massive commit log diff](http://keepachangelog.com/en/1.0.0/#bad-practices) but the new `commit-limit` flag means devs can do whatever they want (thanks again @eliperelman). 3 just seemed like a nice number for creating changelogs that weren't too verbose or sparse.

This is by far the most popular repo using `auto-changelog` so I'm happy to work on making it more flexible if there are other things you guys think would improve it. I've noticed that it isn't parsing some of your merge commits correctly, for example, so I'll take a look at that.

>At the moment, since Neutrino isn't using the "fixes" notation recognised by auto-changelog, everything has been split out into "merged" and "commits", which seems a bit arbitrary.

`auto-changelog` just uses the [notation that GitHub uses](https://help.github.com/articles/closing-issues-using-keywords/).

**Pull request merged**
