### PR TITLE
Throw more useful errors when missing commands

### LINKED ISSUE #390: Running neutrino with no command specified gives TypeError
If the command is accidentally omitted, it results in the following:
```
$ yarn neutrino
yarn run v1.2.1
$ C:\Users\Ed\src\treeherder\node_modules\.bin\neutrino
\ Running undefinedC:\Users\Ed\src\treeherder\node_modules\neutrino\bin\execute.js:19
  api.register(`${commandName}-cli`, (config, api) => api.commands[commandName](config, api));
                                                                               ^

TypeError: api.commands[commandName] is not a function
    at Object.api.register [as undefined-cli] (C:\Users\Ed\src\treeherder\node_modules\neutrino\bin\execute.js:19:80)
    at ChainAction.Future.try.chain.chain.chain [as mapper] (C:\Users\Ed\src\treeherder\node_modules\neutrino\src\api.js:170:49)
    at ChainAction$resolved [as resolved] (C:\Users\Ed\src\treeherder\node_modules\fluture\index.js:798:27)
    at resolved (C:\Users\Ed\src\treeherder\node_modules\fluture\index.js:213:19)
    at Immediate.EncaseP2$res [as _onImmediate] (C:\Users\Ed\src\treeherder\node_modules\fluture\index.js:1840:7)
    at runCallback (timers.js:787:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

Ideally the usage information would be given instead.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #390.

### CODE REVIEW

**Review by edmorley — COMMENTED** [review]
Should we have a test for this?

**Comment by eliperelman** [comment]
Ooo good idea.

**Comment by eliperelman** [comment]
Added tests for `run()` and `call()` with non-registered commands.

**Review by edmorley — APPROVED** [review]
Many thanks!

**Pull request merged**
