### PR TITLE
Adding dynamic import capabaility via import()

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by eliperelman** [comment]
I think we also need `babel-plugin-syntax-dynamic-import` for the Node.js preset, but I haven't tested it yet.

**Comment by eliperelman** [comment]
I haven't gotten this to work on Node.js, and I've filed an issue on the env preset on Babel to try and pin it down.

**Comment by helfi92** [comment]
ouch...ok. keep us updated

**Comment by eliperelman** [comment]
@helfi92 according to the Webpack docs, it seems like it should be possible, but I'm having a terrible time trying to get babel-preset-env to work with `async import()` in Node.js:

https://webpack.js.org/guides/code-splitting-import/

**Comment by helfi92** [comment]
@eliperelman According to the [usage with babel and async await guidelines](https://webpack.js.org/guides/code-splitting-import/#usage-with-babel-and-async-await), to use `async/await` with `import()` we need `syntax-dynamic-import`, `transform-async-to-generator`, `transform-regenerator`,        `transform-runtime` as plugins. Are those taken care of with `babel-preset-env`?

**Comment by eliperelman** [comment]
They theoretically should be excluded (the regenerator stuff), because Node.js 6.9 supports generators. We only need it to transform async to generator, which happens, but then messes up some regenerator stuff.

**Comment by eliperelman** [comment]
Blocked by https://github.com/babel/babylon/issues/378

**Comment by helfi92** [comment]
@eliperelman Seems like they fixed it

**Comment by eliperelman** [comment]
Haha, I was literally just looking into it. For it to be fixed in Webpack, this change needs to make it in:

https://github.com/kesne/acorn-dynamic-import/pull/5

Right now Webpack v2.2.1 is on acorn-dynamic-import v2.0.0, and we need it to be v2.0.2 for the dynamic import fix.

**Comment by eliperelman** [comment]
Derp, webpack uses version ranges, so I just need to regenerate the yarn.lock and it should be OK.

**Comment by eliperelman** [comment]
Note that we still need the babylon fix since babel-preset-env is doing work here and needs to parse the syntax. Looking at the changelog for babylon, this might not happen until Babel 7.

**Comment by eliperelman** [comment]
I think we should probably move forward with dynamic imports for Web only for now, since it will break down dynamic imports to ES5 friendly code based on the current babel-preset-env targets. Thoughts?

**Comment by helfi92** [comment]
@eliperelman Sure, let's worry about making it work on Node later. For now, we can make it work on web. We can then put your suggested changes to react-router-starter and have people use it :)

**Comment by eliperelman** [comment]
Resolving in #86.

**Pull request closed without merging**
