### PR TITLE
Adding getters and setters for path options, options for middleware

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by timkelty** [comment]
Tested setting `source`, `output`, and `entry` with relative paths from middleware - works for me!

I'm not sure how important it is - but it seems there still isn't really a good way to (re)set the defaults, but still allow overrides from package.json.

**Comment by timkelty** [comment]
Thanks! Eagerly awaiting a release :)

**Comment by eliperelman** [comment]
@timkelty it's already released, in v5.5.0! :tada:

**Comment by timkelty** [comment]
BOSS.

**Pull request merged**
