### PR TITLE
Nest create-new-project under installation and link to it from index

### PR DESCRIPTION
**Pull request by timkelty**
Thought it made sense for newcomers to see create-project linked to up-front.

Related: https://github.com/mozilla-neutrino/neutrino-dev/pull/610

### CODE REVIEW

**Comment by timkelty** [comment]
Just checked - that was the only place I could find.

**Comment by eliperelman** [comment]
Ah I see, I was getting confused with #610. With that now merged, I think the links in there now need to be updated. Sorry!

**Comment by timkelty** [comment]
Ok - rebased off master and applied these changes. Also stole some of the language used in #610 so they match up.

**Comment by timkelty** [comment]
On a side note - I noticed there is no `docs/packages/create-project`… is that intentional?

**Comment by eliperelman** [comment]
@timkelty yes intentional. `packages` are for middleware, while `neutrino` and `create-project` are split out.

**Pull request merged**
