### PR TITLE
Move from package.json configuration to .neutrinorc.js, allow CLI options

### PR DESCRIPTION
**Pull request by eliperelman**
Everything seems to be working so far. I have a local node, react, and web project with the following `.neutrinorc.js` files in each respectively:

```js
// node project
module.exports = neutrino => {
  neutrino.use('neutrino-preset-node', {
    babel: {
      plugins: [require.resolve('babel-plugin-transform-react-jsx')]
    }
  });
  neutrino.use('neutrino-preset-mocha');
};
```

```js
// react project
module.exports = {
  use: [
    'neutrino-preset-react',
    'neutrino-preset-jest'
  ],
  env: {
    production: {
      options: {
        output: 'dist'
      },
      use: [
        neutrino => neutrino.config.merge({
          entry: {
            vendor: [
              'react',
              'react-dom'
            ]
          },
          "module": {
            "rule": {
              "style": {
                "use": {
                  "css": {
                    "options": {
                      "modules": true
                    }
                  }
                }
              }
            }
          }
        })
      ]
    }
  }
};
```

```js
// web project
module.exports = {
  use: [
    'neutrino-preset-airbnb-base',
    ['neutrino-preset-web', { devServer: { port: 5769, host: '192.168.0.107' } }],
    'neutrino-preset-karma'
  ]
};
```

### CODE REVIEW

**Comment by eliperelman** [comment]
I've also removed all environment variables at the moment. This means that all IP lookups were removed and must be manually passed into the middleware in `.neutrinorc.js`.

**Comment by eliperelman** [comment]
This will resolve #199.

**Comment by eliperelman** [comment]
I'm going to change the `.env` layout to accommodate accepting command line options and a complex env structure.

**Comment by eliperelman** [comment]
This PR now also addresses #165. Here is an updated react example based on the one above:

```js
// react project
module.exports = {
  use: [
    'neutrino-preset-react',
    'neutrino-preset-jest'
  ],
  env: {
    NODE_ENV: {
      production: {
        options: {
          output: 'dist'
        },
        use: [
          neutrino => neutrino.config.merge({ entry: { vendor: ['react','react-dom'] } })
        ]
      }
    }
  }
};
```

`env` is now an object instead of a single value. This means you can configure based on arbitrary envs passed to Neutrino:

```js
module.exports = {
  env: {
    ALPHA: {
      // The following middleware is used when `neutrino.options.env.ALPHA === 'beta'`
      beta: { ... }
    }
  }
};
```

You can now also set Neutrino options and environment variables from the command line:

```sh
neutrino start --options.output dist --options.env.NODE_ENV production --options.env.ALPHA beta
```

**Comment by eliperelman** [comment]
I've added back the ability to configure the dev server from the command line, although with different options now, no environment variables:

```sh
neutrino start --options.host something.local --options.port 3000 --options.https
```

Nested booleans don't work out of the box with strings, so setting something to "false" will take manual parsing in middleware, e.g. you can't do this without parsing:

```sh
neutrino start --options.https false
```

Other than that, it works well!

**Comment by constgen** [comment]
Why not this layout for the "use"?
```js
module.exports = ({
  use: [
    'alpha',
    {
      use: 'neutrino-preset-web',
      options: {
        devServer: {
          port: 3000
        }
    },
    neutrino => {
      // whatever
    }
  ]
});
```

**Comment by rodgobbi** [comment]
Should the CLI options be working on version `6.2.1`?
I've tried to inject an env variable via CLI but it always returns `undefined`.

**Comment by eliperelman** [comment]
@rodgobbi it's possible there is a bug in that version. Could you provide a simplified test case repo to reproduce?

**Comment by rodgobbi** [comment]
@eliperelman thank you for your attention. I just pass in to the `start` script the command: `neutrino start --options.env.ALPHA test` and it prints `undefined` the line `console.log(process.env.ALPHA)`.

**Comment by eliperelman** [comment]
@rodgobbi is the `console.log` in the application, or a file being `use`d by Neutrino?

**Comment by eliperelman** [comment]
I just downloaded Neutrino v6.2.1 and ran used the following `test.js` file:

```js
module.exports = (neutrino) => {
  console.log('\n\n', process.env.ALPHA, '\n\n');
};
```

```bash
❯ yarn neutrino start --options.env.ALPHA beta --use test.js
yarn run v1.5.1
warning package.json: No license field
$ /private/var/folders/dl/9lrzd5110zlft676qdpr7xn40000gp/T/repro/node_modules/.bin/neutrino start --options.env.ALPHA beta --use test.js
⠋ Building project

 beta
```

So this part seems to work for me

**Comment by eliperelman** [comment]
You would need to be using some env middleware. If you have some code I could view, I could help give you a more definitive answer.

**Comment by rodgobbi** [comment]
I understand, I thought I could pass it directly, it won't be possible for me to show any code today, but I'll try the Middleware tomorrow, or soon as I can. Thanks a lot for the help.

**Comment by eliperelman** [comment]
@rodgobbi sure thing. The reason we rely on middleware for you to be explicit about what env vars to inject comes down to security. If we placed all env vars into the bundle, it unintentionally inject private information. Let me know if I can help you out more tomorrow.

**Comment by rodgobbi** [comment]
@eliperelman I've installed the `@neutrinojs/env` and I don't know why, it only works if I put it in the end of the `use` array, after the `neutrino-preset-react`, but still, I got what I needed. Before putting it to work (when I put it on the beginning of the `use` array), I was getting really frustrated hehehhe, if you have any idea why did this happen, I'm curious to hear. And thanks a lot for the fast and good support!

**Comment by eliperelman** [comment]
@rodgobbi that's because the react preset internally also uses this preset. If you put it before, the react preset values will override it.

**Pull request merged**
