### PR TITLE
react-hot-loader is no longer beta

### PR DESCRIPTION
**Pull request by helfi92**
react-hot-loader [CHANGELOG](https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md)'s for reference.

### CODE REVIEW

**Comment by eliperelman** [comment]
I'll get this merged and shipped soon.

**Comment by eliperelman** [comment]
Will ship in a minor release.

**Comment by edmorley** [comment]
> Will ship in a minor release.

Please can we hold off doing another release for a few days? Given that we republish all packages every time we publish, I think it would be good to start batching changes up a bit, rather than releasing multiple times a week :-)

**Comment by eliperelman** [comment]
Yeah, I'm not publishing until we have all the latest PRs merged.

**Pull request merged**
