### PR TITLE
Improve error messaging for middleware used with no entry point

### LINKED ISSUE #384: Improve error message if entrypoint missing
Currently using this config:
```js
// .neutrinorc.js
module.exports = {
  use: [
    'neutrino-middleware-eslint',
  ]
};
```

Or more simply, running `yarn neutrino build --use neutrino-middleware-eslint`, results in:

```
× Building project failed
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration misses the property 'entry'.
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
    at ChainAction.validator.chain.errors [as mapper] (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\neutrino\src\webpack.js:49:20)
    at ChainAction$resolved [as resolved] (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:798:27)
    at resolved (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:213:19)
    at Resolved._fork (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:636:3)
    at drain (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:270:25)
    at settle (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:199:15)
    at resolved (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:213:5)
    at Immediate.EncaseP2$res (C:\Users\Ed\Desktop\preset-eslint-issue\node_modules\fluture\index.js:1840:7)
    at runCallback (timers.js:787:20)
    at tryOnImmediate (timers.js:747:5)
```

Ideally Neutrino would explain that "A preset or middleware that defines an entrypoint has not been found, see: ..." etc.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #384.

### CODE REVIEW

**Review by edmorley — APPROVED** [review]
Look great! :-)

**Review by edmorley — COMMENTED** [review]
Actually, I don't suppose you could add a test here too, seeing as we already have some prior art for testing `options.entry`?

**Comment by eliperelman** [comment]
@edmorley I added a test, but in doing so changed a few things. I didn't want to put references to the CLI in an error generated by the API, so I made it generic, then re-handled in the CLI. To make this consistent across all commands, I made each CLI command call a common base which removes a lot of the boilerplate that every command was doing.

Hopefully this brings more simplicity and consistency to our handling from the CLI.

**Comment by edmorley** [comment]
Even better! :-)

**Pull request merged**
