### PR TITLE
Sort create-project dependencies and devDependencies

### LINKED ISSUE #853: Sort create-project's "Installing devDependencies" console output
Somewhat nit-picky, but currently create-project outputs:
```
Installing dependencies: prop-types, react, react-dom, react-hot-loader
⏳  Installing devDependencies: @neutrinojs/react, neutrino, webpack, webpack-cli, webpack-dev-server, @neutrinojs/jest, jest, @neutrinojs/airbnb, eslint
```

I think the dependencies/devDependencies should be sorted in alphabetical order (or at least with the Neutrino deps consecutively).

### PR DESCRIPTION
**Pull request by helfi92**
Resolves #853.

### CODE REVIEW

**Comment by edmorley** [comment]
create-project may be removed as part of #852 so cancelling the review for now

**Comment by eliperelman** [comment]
Looks like we need a rebase here.

**Comment by helfi92** [comment]
Rebased.

**Review by edmorley — COMMENTED** [review]
The sort order with this gives eg:
`eslint, jest, neutrino, @neutrinojs/airbnb, @neutrinojs/jest, @neutrinojs/react, webpack, webpack-cli, webpack-dev-server`

Looks neater, though I'm on the fence as to whether the added complexity of a custom sort function is worth it, since the default `.sort()` would give:
`@neutrinojs/airbnb, @neutrinojs/jest, @neutrinojs/react, eslint, jest, neutrino, webpack, webpack-cli, webpack-dev-server`

...which is consistent with the package.json order, even if the neutrino deps aren't all consecutive. 

Is up to you :-)

**Comment by helfi92** [comment]
No strong feelings here. Feel free to close it if it's too much added complexity :)

**Comment by edmorley** [comment]
I don't mean close, I mean `dependencies.sort()` vs `dependencies.sort(customSortFunction)` :-)

**Review by edmorley — APPROVED** [review]
Many thanks!

(Travis is failing - I believe due to a bug with either verdaccio or lerna when the auto-generated test package version SHA is numeric only and starting with a zero. I'll, try and track this down separately, but needn't block merging)

**Pull request merged**
