### PR TITLE
chore: Add lint-staged and husky

### PR DESCRIPTION
**Pull request by okonet**
Add lint-staged with an auto-fix configuration for all JS files.

See https://github.com/okonet/lint-staged

### CODE REVIEW

**Comment by constgen** [comment]
Are you sure you want to automatically add all files to stage. Somebody may commit some trash and even will not notice this. Please disable this

**Comment by okonet** [comment]
What do you mean? This will prevent committing trash. Please read my post.

**Comment by okonet** [comment]
This won't add all files to stage. All commands run only on staged files so it only add same files back after fixing eslint rules that are auto-fixable I.e. prettier.

**Comment by constgen** [comment]
I was wrong. Didn't realize how `lint-staged` works. `git add` confused me. I take my words back.

**Pull request merged**
