### PR TITLE
Allow using a custom entry for Node.js preset

### LINKED ISSUE #468: Not able change entry
I would like to change for node js development index.js to server.js but I get error when I rename index.js to server.js 

/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81
      var existsAt = compilation.assets[name].existsAt;
                                              ^

TypeError: Cannot read property 'existsAt' of undefined
    at StartServerPlugin.startServer (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:81:47)
    at StartServerPlugin.afterEmit (/home/lubo08/workspace/bimp/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:54:12)
    at Compiler.applyPluginsAsyncSeries1 (/home/lubo08/workspace/bimp/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/lubo08/workspace/bimp/node_modules/webpack/lib/Compiler.js:354:15)
    at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:1050:13)
    at /home/lubo08/workspace/bimp/node_modules/webpack/node_modules/async/dist/async.js:958:16
    at /home/lubo08/workspace/bimp/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:137:15) 
neutrino config is 

module.exports = {
  options: {
    // Override to relative file, resolves to options.source + entry.*
    entry: 'server',
  },
  use: [
    'neutrino-preset-node',
    'neutrino-preset-airbnb-base'
  ]
};

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #468.

### CODE REVIEW

**Review by edmorley — APPROVED** [review]
Would a test for this be easy? (Given our minimal tests so far)

**Comment by edmorley** [comment]
I wonder as well whether we should do this for the web preset too? For multi-entrypoint support I guess we'll need to.

**Comment by eliperelman** [comment]
> Would a test for this be easy? (Given our minimal tests so far)

I'll have a look to see.

> I wonder as well whether we should do this for the web preset too? For multi-entrypoint support I guess we'll need to.

My thoughts exactly, and I was working to incorporate these into master.

**Comment by eliperelman** [comment]
Added test for custom entry.

**Pull request merged**
