### PR TITLE
Use scoped packages under the @neutrinojs org

### LINKED ISSUE #413: Migrate packages to scoped npm namespace
Right now if we want to support official packages, we have to deal with conflicting names in the community. If we move to scoping the packages under an npm org, we would be able to work around this. I created the `@neutrinojs` org, since neutrino was already in use. We could explore this for v8.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #413.

### CODE REVIEW

**Review by edmorley — CHANGES_REQUESTED** [review]
Looks good so far, though I see quite a few `neutrino-{preset,middleware}-` references still left? (eg docs and package.json repository links)

Also, what is the plan for informing existing users that they need to migrate? People relying on greenkeeper/renovate might not know there is a new package name unless we do a another release under the old package names that gives console.warn() deprecation warnings or similar.

**Comment by eliperelman** [comment]
Yeah, I'll think we will issue deprecation messages once we release v8. Fortunately we've been using peerDependencies, so it shouldn't be too big of a deal. With a major release comes breaking changes, and it should be simple enough for most to just switch packages.

Regarding the references, yeah, I haven't done any docs work yet, but package.jsons should be fixed, so that's my mistake. I'll take a look.

**Comment by eliperelman** [comment]
OK, I think I have all the references updates from docs.

**Comment by edmorley** [comment]
```
neutrino-dev $ rg 'neutrino-(middleware|preset)-' -g '!CHANGELOG.md'
docs\creating-presets.md
100:mkdir neutrino-preset-standard-style && cd neutrino-preset-standard-style

docs\upgrading-neutrino.md
17:copying directives using the `neutrino-middleware-copy` middleware.
25:e.g. `neutrino.use(minify, { minify: {}, plugin: {} })` or `['neutrino-middleware-minify', { minify: {}, plugin: {} }]`.

docs\api\README.md
386:For a concrete example, the [eslint middleware](../middleware/neutrino-middleware-eslint) registers an `eslintrc`
452:run('build', ['neutrino-preset-react'])
485:api.run('start', ['neutrino-preset-react'])
498:api.use('neutrino-preset-react');
523:api.run('build', ['neutrino-preset-node'])
536:api.use('neutrino-preset-node');
569:api.run('test', ['neutrino-preset-node', 'neutrino-preset-mocha'])
585:api.run('test', ['neutrino-preset-node', 'neutrino-preset-mocha'])
598:api.use('neutrino-preset-node');
599:api.use('neutrino-preset-mocha');
629:api.run('inspect', ['neutrino-preset-node'])
642:api.use('neutrino-preset-node');

packages\web\package.json
14:  "repository": "https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/neutrino-preset-web",
```

**Comment by eliperelman** [comment]
lol nice find!

**Comment by eliperelman** [comment]
Updated again, but leaving out upgrading-neutrino and creating-presets since those are not really relevant to this PR.

**Review by edmorley — APPROVED** [review]

**Comment by eliperelman** [comment]
Yay!

**Pull request merged**
