### PR TITLE
v9.0.0-rc.5

### PR DESCRIPTION
**Pull request by edmorley**
Generated using the process here:
https://master.neutrinojs.org/contributing/development/#releasing-a-new-version

Changelog:
https://github.com/neutrinojs/neutrino/compare/v9.0.0-rc.4...2e202138311e3c0c5f1e6f53896f28202f696154

### CODE REVIEW

**Comment by edmorley** [comment]
Presuming there are no issues with this RC release, I'd like to release v9 final a few days after this.

**Comment by edmorley** [comment]
Any takers for review? :-)

**Comment by timkelty** [comment]
@edmorley on my list this morning!

**Review by timkelty — COMMENTED** [review]
Sorry for the delay @edmorley, looks great.

**Comment by edmorley** [comment]
No worries - would have waited longer but wanted to get it done before work :-)

**Pull request merged**
