### PR TITLE
Eslint babel quotes

### PR DESCRIPTION
**Pull request by patiboh**
Fix for issue #788

### CODE REVIEW

**Comment by edmorley** [comment]
Sorry to be a pain, but after chatting to @eliperelman we think it might be best to also make the same change to the `airbnb-base` preset too, just to keep them in sync (and in case people using the Vue preset use `airbnb-base` instead).

As such, would you mind also updating `packages/airbnb/index.js`?

**Comment by patiboh** [comment]
Sure , I'll do it :)

**Comment by edmorley** [comment]
Ah yes that's the one - I pasted the wrong filename haha!

**Comment by edmorley** [comment]
Many thanks for the PR!
This change will be in Neutrino 9 (when it is released) :-)

**Comment by patiboh** [comment]
Great! :)

**Pull request merged**
