### PR TITLE
Create project refactor and use react hooks implementation

### LINKED ISSUE #1198: React create-project example page text is missing a space between words
### STR:

1. `yarn global add @neutrinojs/create-project@next`
2. `create-project test`
3. Pick "react" and "airbnb"
3. `cd test && yarn start`

### Expected:

Page says `Welcome to test`.

### Actual:

Page says `Welcome totest`. (ie missing a space)

This is because of the wrapping here (which iirc was written that way to keep eslint happy):
https://github.com/neutrinojs/neutrino/blob/148de457f1e679b694781f1454369c96ecb706de/packages/create-project/commands/init/templates/react/src/App.jsx#L14-L17

### LINKED ISSUE #1332: create-project React Hooks
The React team [recommends](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both) using Hooks instead of classes for new components. When using the create-project helper, `App.jsx` uses a class. We should consider moving away from a class and use a normal function instead. The reason I am suggesting this is because hooks cannot be used inside a class.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #1332.
Fixes #1198.

### CODE REVIEW

**Review by helfi92 — COMMENTED** [review]
Love the refactor and the react hooks implementation :) I tried running the create-project scripts but it's throwing an error during `yarn start`:

```bash
An error occurred when loading the Neutrino configuration.

TypeError: neutrino.use is not a function
```

I wonder if I'm doing anything wrong. Here's the generated `.neutrinorc.js`:

```js
const react = require('@neutrinojs/react');
const jest = require('@neutrinojs/jest');

module.exports = {
  options: {
    root: __dirname,
  },
  use: [
    react({
      html: {
        title: 'create-project-with-hooks'
      }
    }),
    jest(),
  ],
};
```

**Comment by eliperelman** [comment]
@helfi92 it seems to be working in travis, could you share the commands you're using so I can try and replicate?

**Comment by helfi92** [comment]
Here are the commands:

```bash
➜  projects ./neutrino-dev/packages/create-project/bin/create-project.js neutrino-create-project
                        _          _
    _ __    ___  _   _ | |_  _ __ (_) _ __    ___
   | '_ \  / _ \| | | || __|| '__|| || '_ \  / _ \
   | | | ||  __/| |_| || |_ | |   | || | | || (_) |
   |_| |_| \___| \__,_| \__||_|   |_||_| |_| \___/

Welcome to Neutrino! 👋
To help you create your new project, I am going to ask you a few questions.

? 🤔  First up, what would you like to create? A web or Node.js application
? 🤔  Next, what kind of application would you like to create? React
? 🤔  Would you like to add a test runner to your project? Jest
? 🤔  Would you like to add linting to your project? None

👌  Looks like I have all the info I need. Give me a moment while I create your project!

   create neutrino-create-project/package.json
   create neutrino-create-project/.neutrinorc.js
   create neutrino-create-project/webpack.config.js
   create neutrino-create-project/src/App.css
   create neutrino-create-project/src/App.jsx
   create neutrino-create-project/src/index.jsx
   create neutrino-create-project/jest.config.js
   create neutrino-create-project/test/simple_test.js

⏳  Installing dependencies: prop-types@^15, react@^16, react-dom@^16, react-hot-loader@^4
⏳  Installing devDependencies: @neutrinojs/react@^9.0.0-0, neutrino@^9.0.0-0, webpack@^4, webpack-cli@^3, webpack-dev-server@^3, @neutrinojs/jest@^9.0.0-0, jest@^24

Hooray, I successfully created your project!

I have added a few yarn scripts to help you get started:
  • To build your project run:  yarn build
  • To start your project locally run:  yarn start
  • To execute tests run:  yarn test
  • To lint your project manually run:  yarn lint
    You can also fix linting problems with:  yarn lint --fix

Now change your directory to the following to get started:
  cd neutrino-create-project

❤️  Neutrino
➜  projects cd neutrino-create-project
➜  neutrino-create-project yarn start
yarn run v1.15.2
warning ../package.json: No license field
$ webpack-dev-server --mode development --open

An error occurred when loading the Neutrino configuration.

TypeError: neutrino.use is not a function
    at module.exports (/Users/haali/Documents/Mozilla/projects/neutrino-create-project/node_modules/@neutrinojs/react/index.js:47:12)
    at Object.<anonymous> (/Users/haali/Documents/Mozilla/projects/neutrino-create-project/.neutrinorc.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireFromRoot (/Users/haali/Documents/Mozilla/projects/neutrino-create-project/node_modules/neutrino/Neutrino.js:34:10)
error Command failed with exit code 1.
```

**Comment by edmorley** [comment]
When testing create-project locally, either it needs to be run with the `--registry` option (after having published to verdaccio locally), or else `yarn link` be run afterwards, so that the newly created project uses the development neutrino packages from the src directory and not the latest published to NPM.

**Review by helfi92 — APPROVED** [review]
Worked smoothly. Awesome work @eliperelman as always!

**Pull request merged**
