### PR TITLE
PWA middleware

### PR DESCRIPTION
**Pull request by eliperelman**
Draft of proposed PWA middleware. The goal of this is to be able to drop into a web project and get SW caching for free with no upfront configuration.

### CODE REVIEW

**Comment by eliperelman** [comment]
This would resolve #27.

**Comment by constgen** [comment]
Can we try to hot reload the application instead of page refresh when new version of resources arrived?

**Comment by eliperelman** [comment]
Hot reload is only enabled in development, and service worker is only enabled in production. Not to mention that HMR is optional, and the concerns are separate from those of SW. In the core case, they aren't related.

**Comment by eliperelman** [comment]
@developit thanks for the 👍!

**Pull request merged**
