### PR TITLE
Fix typo in command to install npx

### PR DESCRIPTION
**Pull request by sylvhama**
Based on https://github.com/zkat/npx#install

### CODE REVIEW

**Comment by edmorley** [comment]
I think this is as-intended? Newer versions of npm come with npx, so the docs are suggesting updating npm rather than manually installing npx?

**Comment by sylvhama** [comment]
@edmorley on Windows 10 it will raise an error when running `npm install -g npm`:
```npm ERR! path C:\Program Files\nodejs\npm.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Program Files\nodejs\npm.cmd
npm ERR! Move it away, and try again.```

I've just used nvm for Windows to install node 9.8.0 which comes with npm v5.6.0. When switching to this version it says that npx is not  recognized.

**Comment by edmorley** [comment]
> on Windows 10 it will raise an error when running npm install -g npm

This sounds like npm/npm#5050

> I've just used nvm for Windows to install node 9.8.0 which comes with npm v5.6.0. When switching to this version it says that npx is not recognized.

I can reproduce on Windows when using nvm-windows (but not with a standard nodejs install) - it looks like this is a known issue with nvm-windows specifically:
coreybutler/nvm-windows/issues/293

I'm torn here. I think generally we should encourage people to be on the latest version of `npm`, so ideally we'd keep that part of the docs, but given it causes an error on Windows, and that the explicit npx install is required when using nvm-windows, perhaps switching the instructions over for now is fine. 

@eliperelman, thoughts?

users of nvm-windows will need to install npx explicitly - so perhaps the docs could say to install

**Comment by eliperelman** [comment]
I think the docs should promote `npx` primarily. To cover this situation, maybe we can add a note underneath it for nvm-windows users.

**Comment by edmorley** [comment]
(And link to that nvm-windows issue)

**Comment by sylvhama** [comment]
Should I close this PR and open a new one based on @edmorley advice?

**Comment by eliperelman** [comment]
@sylvhama sure, I think that sounds like a simple solution.

**Comment by eliperelman** [comment]
Closing per https://github.com/mozilla-neutrino/neutrino-dev/pull/732#issuecomment-390821358.

**Pull request closed without merging**
