### PR TITLE
Pluggable event architecture mode, new test presets

### PR DESCRIPTION
**Pull request by eliperelman**
@helfi92 forgive me :laughing:

So, this patch attempts to make Neutrino a bit more pluggable. By defining new events that preset authors can attach to, they can hook into the lifecycle of Neutrino and make changes.

What this means for the "test" command is that without a preset that's listening for the "test" event, it will essentially do nothing. It is up to test preset authors to listen for this event, do some kind of build or compilation if necessary, then execute tests. You can see how I accomplished this with 3 different test presets: mocha, Karma, and Jest.

Let me know what you think. I'll merge this probably tomorrow, then start in on docs.

### CODE REVIEW

**Comment by eliperelman** [comment]
This pull request solves issues #7, #8, and #9.

**Comment by helfi92** [comment]
@eliperelman It looks great :) How can I run it locally.

`yarn && yarn clean-all && yarn-bootstrap` on neutrino-dev and `yarn link neutrino neutrino-preset-react` on a react project is not working for me.

**Comment by eliperelman** [comment]
If you are already bootstrapped, you can just run `yarn link-all` and it will set up the links.
You are already linking in the dependent project which is fine.

I know it's dumb, but I also have to run `npm i eslint-plugin-react` in `packages/neutrino-preset-base`.

What error do you get?

**Comment by eliperelman** [comment]
This should also fix #11.

**Comment by helfi92** [comment]
Ok so I did what you suggested, but without success. I am getting:

```
TypeError: Cannot read property 'node' of undefined
at emitForAll.then (/Users/hassanali/Documents
/Mozilla/projects/neutrino-dev/packages/neutrino/src/neutrino.js:118:26)
```

Any thoughts?

**Comment by eliperelman** [comment]
Were you trying this in a Node project?

**Comment by helfi92** [comment]
I was trying it with treeherder-manifest

**Comment by helfi92** [comment]
I'll try one more thing, give me a moment

**Comment by helfi92** [comment]
Argh, it's still failing. When I try it on the master branch, it works.

I also tried deleting the neutrino-dev and downloading only the branch with:

```
git clone -b plugin-mode https://github.com/mozilla-neutrino/neutrino-dev.git
yarn && yarn bootstrap
```

I deleted treeherder-manifest, cloned it back again and did:

```
yarn && yarn link neutrino neutrino-preset-react
yarn run start
```

I get the same error in my earlier comment.

**Comment by eliperelman** [comment]
Nuts, ok I'll try and replicate.

**Comment by eliperelman** [comment]
@helfi92 can you try upgrading your installation of Yarn? https://yarnpkg.com/en/docs/install

**Comment by helfi92** [comment]
I upgraded to yarn version 0.19.1. I redid the steps of my last comment but I have still have the same error. Did you try replicating my steps to see if it works on your machine?

**Comment by eliperelman** [comment]
I seem to have problems too when starting from scratch. Maybe it's a problem with yarn-autolink. I'll see if putting a different solution in place will help.

**Comment by eliperelman** [comment]
@helfi92 ok, I think I have most of the kinks worked out. I'm using a different monorepo package that seems to work well. I also added eslint-plugin-react to the base preset's dev dependencies.

So, the process should be:

- In neutrino-dev: `yarn && yarn bootstrap`
- In treeherder-manifest: `yarn && yarn link neutrino neutrino-preset-react`
- In treeherder-manifest, edit package.json and change `config.preset` to `config.presets`.

Let me know.

**Comment by helfi92** [comment]
@eliperelman Worked from the first try :)

By the way, I think HMR is not working. Previously we made sure react-hot-loader/patch appeared first in the `entry.index` using `unshift`. `config.entry.index.unshift(require.resolve('react-hot-loader/patch'));`. Is this still occuring with the new changes?

**Comment by helfi92** [comment]
Ah, I get the following error in the console:

`React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.`

**Comment by eliperelman** [comment]
OK, my mistake. Will update. Glad to hear the repo is working now. :)

**Comment by eliperelman** [comment]
@helfi92 ok, updated. I had to add a method to webpack-chain to allow prepending to an entry instead of only appending.

**Comment by eliperelman** [comment]
Going to merge so we can continue to iterate.

**Comment by helfi92** [comment]
@eliperelman, thanks for adding `prepend`. I took a look and I had to make 2 small changes to make HMR work. We need a hot property in `config.devServer`.

First, replace `add` in `.add(require.resolve('react-hot-loader/patch'));` with `prepend` to make use of the new functionality :)

Second, add the following method inside `webpack-chain/DevServer`

```javascript
  hot(hot) {
    return this.set('hot', hot);
  }
```
After that, in `neutrino-preset-web`, append `.hot(true)`to `config.devServer`.

**Comment by eliperelman** [comment]
@helfi92 I thought you couldn't use the `hot` property with the `HotModuleReplacementPlugin`. Am I wrong?

**Comment by helfi92** [comment]
@eliperelman According to [dan's post](https://github.com/gaearon/react-hot-loader/issues/243/#issuecomment-211957140) about enabling HMR, we need both.

**Comment by eliperelman** [comment]
@helfi92 awesome!

**Comment by eliperelman** [comment]
Actually, following the steps in your comment blows up for me. According to that link, we need to wrap the root element we are rendering in an `AppContainer` exported from `react-hot-loader`. This will probably need to be pushed into the dependent project if they want to enable hot reloading. Lemme see if I can get a PR open to demonstrate.

**Comment by helfi92** [comment]
@eliperelman Try this one: https://github.com/helfi92/neutrino-test

**Comment by eliperelman** [comment]
@helfi92 I'm trying it against treeherder-manifest and all I get is this:

error

**Comment by eliperelman** [comment]
Let's move this conversation to #15.

**Pull request merged**
