### PR TITLE
Enable jest coverage for all neutrino extensions

### LINKED ISSUE #643: Coverage report is missing when using Jest and neutrino v7
When using neutrino v7 with Jest preset, the coverage report is missing reporting:

```
Test Suites: 23 passed, 23 total
Tests:       1 skipped, 150 passed, 151 total
Snapshots:   105 passed, 105 total
Time:        11.409s
Ran all test suites.
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

It was working in v6

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #643.

@okonet if you apply this patch locally, does it fix the issue for you?

### CODE REVIEW

**Comment by okonet** [comment]
No, this doesn't change anything for me.

**Comment by eliperelman** [comment]
@okonet do you have a repo or test case I can try it on?

**Comment by okonet** [comment]
I don't have a repro yet but here is the debug information from my project:

```
 "collectCoverageFrom": [
      "app/**/*.{js,jsx,vue,ts,mjs}"
    ],
```

for the `.neutrinorc`

```
  options: {
    source: 'src/content/app',
    tests: 'src',
    mains: {
      index: 'web-main.js',
    },
    output: 'build/release/web',
  },
```

Since I'm co-locating tests with implementation I set the `test` to `src` which worked well until v7.

Note how the whole `src/content` part is missing in Jest config.

**Comment by okonet** [comment]
Making it a relative path _does print coverage_ but also for all unrelated (i.e. without tests) files.

**Comment by okonet** [comment]
I just checked the report prior v7 and it looks like `collectCoverageFrom` wasn't even set so I'm wondering why did you decide to change this from `undefined` to a specific value?

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/neutrino-dev/issues/351

**Comment by okonet** [comment]
Okay, so I think the solution should be to get the _relative_ path but with the `src/content` part. Not sure why it gets stripped in my case. Ideas?

**Comment by eliperelman** [comment]
@okonet any reason your `source` can't stay as `src`?

**Comment by eliperelman** [comment]
Nevermind, I misread something.

**Comment by eliperelman** [comment]
Closing, superseded by #659.

**Pull request closed without merging**
